name: cpu-forecast-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - pandas==2.1.0
    - numpy==1.26.0
    - scikit-learn==1.3.0
    - xgboost==2.0.3
    - joblib==1.3.2
    - flask==3.0.0
    - requests==2.31.0
    - azure-ai-ml==1.13.0
    - azure-identity==1.14.0
